# This file was generated by GoReleaser. DO NOT EDIT.
cask "coggo" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "33436475f220a19b78846cd4293f2574e63fe332baa3f0a1bf2571b7354645c0"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0260b51903f9496061876a4230fd3ba1c34dd400f95cc4ce2fc90bc6ba3be212"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57fc53a323286583f91b33dd08efa8f60ffa0d739042f11fb391212b1c3ae102"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "05bedbe5d1541f342d4689ca098f835b462b74ec26a49def882e0ab6d0c4ebd6"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "coggo"
  desc "Durable shared context for Claude Code, Codex, claude.ai, and other MCP-capable agents."
  homepage "https://github.com/lunguini/coggo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coggo"
  binary "coggo-oauth-gateway"

  # No zap stanza required

end
