# This file was generated by GoReleaser. DO NOT EDIT.
cask "coggo" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "dc0ea3ad076af62c06aed828e16e055f86243cee060c99abe178f17b9a5237d4"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f2bb5fd61f540f35476163395d562dfb7b3e855e48d8d9eab169087fc8ea130f"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "afcc7598132dea6bb2686f7637000e03cc3cf3b3fec9cadb00fde7597f08811c"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8090bfcbbbe953b30f021e4db116e29d93f02058ab8a4749cd06879adc5d47fc"
      url "https://github.com/lunguini/coggo/releases/download/v#{version}/coggo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "coggo"
  desc "Durable shared context for Claude Code, Codex, claude.ai, and other MCP-capable agents."
  homepage "https://github.com/lunguini/coggo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coggo"
  binary "coggo-oauth-gateway"

  # No zap stanza required

end
