# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocker < Formula
  desc "Docker-compatible CLI for Apple Container on macOS. Hardware-level isolation via Virtualization.framework."
  homepage "https://github.com/lunguini/gocker"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.2/gocker_0.6.2_darwin_amd64.tar.gz"
      sha256 "eca2686c00d1d2fe4c5ca6ca2262e12995e09e68236f96e76ff031b5bcb62b7d"

      define_method(:install) do
        bin.install "gocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.2/gocker_0.6.2_darwin_arm64.tar.gz"
      sha256 "aa5062e1899a6915832b555d777984734ad3225327e57eca130381aa04b1ceb1"

      define_method(:install) do
        bin.install "gocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.2/gocker_0.6.2_linux_amd64.tar.gz"
      sha256 "b4c61d873dd6662f0544459073075784770795224aa40fa1187c9b76aad76af0"
      define_method(:install) do
        bin.install "gocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.2/gocker_0.6.2_linux_arm64.tar.gz"
      sha256 "be58259b554c7a2af760a1d8f4fa2cbe951d5734a971e891574fa3dbb5055c99"
      define_method(:install) do
        bin.install "gocker"
      end
    end
  end

  test do
    system "#{bin}/gocker", "--version"
  end
end
