# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocker < Formula
  desc "Docker-compatible CLI for Apple Container on macOS. Hardware-level isolation via Virtualization.framework."
  homepage "https://github.com/lunguini/gocker"
  version "0.6.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.4/gocker_0.6.4_darwin_amd64.tar.gz"
      sha256 "3f44bbdc93a4399ce6ba2c92a8d85d6795e487cad460bb2b99faf515389ad899"

      define_method(:install) do
        bin.install "gocker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.4/gocker_0.6.4_darwin_arm64.tar.gz"
      sha256 "38447b67b087d2c7b986d242f747b544cfdd8989211e32e2b6fca0a78002bf8a"

      define_method(:install) do
        bin.install "gocker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.4/gocker_0.6.4_linux_amd64.tar.gz"
      sha256 "45cec26971262a38a1f001d6f1f4b937c056432be64e7fe11b79a6e711e4a890"
      define_method(:install) do
        bin.install "gocker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lunguini/gocker/releases/download/v0.6.4/gocker_0.6.4_linux_arm64.tar.gz"
      sha256 "9adedc99b3971cd358065b26d8076c190bbc788a90015706eb2218dbba140184"
      define_method(:install) do
        bin.install "gocker"
      end
    end
  end

  test do
    system "#{bin}/gocker", "--version"
  end
end
